version: 2

models:
  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: order_status
        tests:
          - accepted_values:
              values: [
                'processing'
                ,'delivered'
                ,'invoiced'
                ,'canceled'
                ,'shipped'
                ,'unavailable'
                ,'created'
                ,'approved'
              ]
  - name: dim_customers
    columns:
      - name : customer_id
        tests : 
          - not_null
          - unique
          
  - name: dim_products
    columns:
      - name : product_id
        tests : 
          - not_null
          - unique
          
  - name: fact_sales
    columns:
      - name: order_id
        tests:
          - not_null
          #- unique #akan gagal karena tabel fact sales gabungan dari order dan order_items

      - name: customer_id
        tests:
          - relationships:
              to: ref('dim_customers')
              field: customer_id

      - name: product_id
        tests:
          - relationships:
              to: ref('dim_products')
              field: product_id
